/* Generated by tools/generate_guest_layout.py. Do not edit. */
#ifndef HV_AUTONOMOUS_LAYOUT_GENERATED_H
#define HV_AUTONOMOUS_LAYOUT_GENERATED_H

#include "types.h"

struct hv_autonomous_layout {
    u32 layout_version;
    u32 cpu_count;
    u64 phys_base;
    u64 ram_end;
    u64 firmware_base;
    u64 firmware_max_size;
    u64 adt_base;
    u64 adt_max_size;
    u64 boot_args_base;
    u64 boot_args_size;
    u64 ramdisk_base;
    u64 ramdisk_max_size;
    u64 low_mem_ipa;
    u64 low_mem_pa;
    u64 low_mem_size;
    u64 virtual_fb_base;
    u32 virtual_fb_width;
    u32 virtual_fb_height;
    u32 virtual_fb_stride;
    u64 pci_ecam;
    u64 pci_bar_window;
    u32 nvme_vintid;
    u64 xhci_base;
};

static const struct hv_autonomous_layout J313_AUTONOMOUS_LAYOUT = {
    .layout_version = 0x1u,
    .cpu_count = 0x8u,
    .phys_base = 0x850000000ull,
    .ram_end = 0xa00000000ull,
    .firmware_base = 0x8510b4000ull,
    .firmware_max_size = 0x1e00000ull,
    .adt_base = 0x851000000ull,
    .adt_max_size = 0xb4000ull,
    .boot_args_base = 0x854000000ull,
    .boot_args_size = 0x4000ull,
    .ramdisk_base = 0x860000000ull,
    .ramdisk_max_size = 0x40000000ull,
    .low_mem_ipa = 0x100000ull,
    .low_mem_pa = 0x8a0100000ull,
    .low_mem_size = 0x3ff00000ull,
    .virtual_fb_base = 0x85f000000ull,
    .virtual_fb_width = 0x500u,
    .virtual_fb_height = 0x320u,
    .virtual_fb_stride = 0x1400u,
    .pci_ecam = 0x690000000ull,
    .pci_bar_window = 0x400000000ull,
    .nvme_vintid = 0x40u,
    .xhci_base = 0x502280000ull,
};

#endif
